#ifndef STORM_ENGINE_COMPATIBILITY_HPP
#define STORM_ENGINE_COMPATIBILITY_HPP
#pragma once

enum class ENGINE_VERSION {
    SEA_DOGS,
    PIRATES_OF_THE_CARIBBEAN, // 2.0
    CARIBBEAN_TALES,
    CITY_OF_ABANDONED_SHIPS, // 2.8
    TO_EACH_HIS_OWN,
    LATEST,
};

#endif // STORM_ENGINE_COMPATIBILITY_HPP
