#pragma once

#include "token.h"

#include <array>

static constexpr const bool ENABLE_SCRIPT_COMPATIBILITY = true;

long func_rand(long max);

template<typename T>
struct TokenTypeFromType;

template<> struct TokenTypeFromType<long> { static constexpr auto type = S_TOKEN_TYPE::VAR_INTEGER; };

//using IntFuncCall = DATA* (*)(DATA *&pVResult, uint32_t arguments);
using IntFuncCall = DATA* (*)();

struct INTFUNCDESC
{
    uint32_t dwArgsNum;
    const char *pName;
    S_TOKEN_TYPE ReturnType;
};

template<typename ReturnType, typename... Args>
static constexpr auto GenerateFuncDesc(const char* name, ReturnType(*func_ptr)(Args... args)) -> INTFUNCDESC {
    return INTFUNCDESC {
        sizeof...(Args),
        name,
        TokenTypeFromType<ReturnType>::type,
    };
}

static constexpr const std::array<INTFUNCDESC, 103> IntFuncTable {
    // {1, "Rand", VAR_INTEGER},
    GenerateFuncDesc("Rand", &func_rand),
    {0, "frnd", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "CreateClass", S_TOKEN_TYPE::VAR_OBJECT},
    {2, "CreateEntity", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "DeleteClass", S_TOKEN_TYPE::TVOID},
    {3, "SetEventHandler", S_TOKEN_TYPE::TVOID},
    {0, "ExitProgram", S_TOKEN_TYPE::TVOID},
    {0, "GetEventData", S_TOKEN_TYPE::UNKNOWN},
    // {1,"Execute",S_TOKEN_TYPE::TVOID},
    {0, "Stop", S_TOKEN_TYPE::TVOID},
    {0, "SendMessage", S_TOKEN_TYPE::VAR_PTR},
    {1, "LoadSegment", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "UnloadSegment", S_TOKEN_TYPE::TVOID},
    {1, "Trace", S_TOKEN_TYPE::TVOID},
    {1, "MakeInt", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "MakeFloat", S_TOKEN_TYPE::VAR_FLOAT},
    {2,"LayerCreate",S_TOKEN_TYPE::TVOID},
    {1,"LayerDelete",S_TOKEN_TYPE::TVOID},
    {1, "LayerDeleteContent", S_TOKEN_TYPE::TVOID},
    {2, "LayerSetRealize", S_TOKEN_TYPE::TVOID},
    {2, "LayerSetExecute", S_TOKEN_TYPE::TVOID},
    {2, "LayerSetMessages", S_TOKEN_TYPE::TVOID},
    {3, "LayerAddObject", S_TOKEN_TYPE::TVOID},
    {2, "LayerDelObject", S_TOKEN_TYPE::TVOID},
    {2, "LayerFreeze", S_TOKEN_TYPE::TVOID},
    {1, "abs", S_TOKEN_TYPE::UNKNOWN},
    {1, "sqrt", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "sqr", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "sin", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "cos", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "tan", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "atan", S_TOKEN_TYPE::VAR_FLOAT},
    {2, "atan2", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "asin", S_TOKEN_TYPE::VAR_FLOAT},
    {1, "acos", S_TOKEN_TYPE::VAR_FLOAT},
    {2, "DeleteAttribute", S_TOKEN_TYPE::TVOID},
    {1, "SegmentIsLoaded", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "GetAttributesNum", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "GetAttributeN", S_TOKEN_TYPE::VAR_AREFERENCE},
    {1, "GetAttributeName", S_TOKEN_TYPE::VAR_STRING},
    {2, "DelEventHandler", S_TOKEN_TYPE::TVOID},
    {1, "EntityUpdate", S_TOKEN_TYPE::TVOID},
    {1, "IsEntity", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "DumpAttributes", S_TOKEN_TYPE::TVOID},
    {1, "sti", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "stf", S_TOKEN_TYPE::VAR_FLOAT},
    {2, "CheckAttribute", S_TOKEN_TYPE::VAR_INTEGER},
    {4, "argb", S_TOKEN_TYPE::VAR_INTEGER},
    {0, "DeleteEntities", S_TOKEN_TYPE::TVOID},
    {0, "ClearEvents", S_TOKEN_TYPE::TVOID},
    {1, "SaveEngineState", S_TOKEN_TYPE::TVOID},
    {1, "LoadEngineState", S_TOKEN_TYPE::TVOID},
    {0, "Event", S_TOKEN_TYPE::TVOID},
    {0, "PostEvent", S_TOKEN_TYPE::TVOID},
    {2, "fts", S_TOKEN_TYPE::VAR_STRING},
    {0, "ClearPostEvents", S_TOKEN_TYPE::TVOID},
    {2, "SetArraySize", S_TOKEN_TYPE::TVOID},
    {1, "GetAttributeValue", S_TOKEN_TYPE::VAR_STRING},
    {1, "Vartype", S_TOKEN_TYPE::VAR_STRING},
    {0, "Breakpoint", S_TOKEN_TYPE::TVOID},
    {2, "Pow", S_TOKEN_TYPE::VAR_FLOAT},
    {2, "CopyAttributes", S_TOKEN_TYPE::TVOID},
    // {2, "GetEntityPointer", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "GetEntityNext", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "GetEntityName", S_TOKEN_TYPE::VAR_STRING},
    {3, "strcut", S_TOKEN_TYPE::VAR_STRING},
    {3, "findSubStr", S_TOKEN_TYPE::VAR_STRING},
    {1, "ClearRef", S_TOKEN_TYPE::TVOID},
    {1, "strlen", S_TOKEN_TYPE::VAR_INTEGER},
    {0, "GetDeltaTime", S_TOKEN_TYPE::VAR_INTEGER},
    {0, "EventsBreak", S_TOKEN_TYPE::TVOID},
    {2, "shl", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "shr", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "and", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "or", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "DeleteEntitiesByType", S_TOKEN_TYPE::TVOID},
    {1, "CreateControl", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "DeleteControl", S_TOKEN_TYPE::TVOID},
    {2, "MapControl", S_TOKEN_TYPE::TVOID},
    {2, "SetControlFlags", S_TOKEN_TYPE::TVOID},
    {1, "ClearEntityAP", S_TOKEN_TYPE::TVOID},
    {1, "GetArraySize", S_TOKEN_TYPE::VAR_INTEGER},
    {0, "GetTargetPlatform", S_TOKEN_TYPE::VAR_STRING},
    {2, "GetEntity", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "FindEntity", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "FindEntityNext", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "GetSymbol", S_TOKEN_TYPE::VAR_STRING},
    {2, "IsDigit", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "SaveVariable", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "LoadVariable", S_TOKEN_TYPE::VAR_INTEGER},
    {2, "SetControlTreshold", S_TOKEN_TYPE::TVOID},
    {2, "LockControl", S_TOKEN_TYPE::TVOID},
    {1, "TestRef", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "SetTimeScale", S_TOKEN_TYPE::TVOID},
    {1, "CheckFunction", S_TOKEN_TYPE::VAR_INTEGER},
    {0, "GetEngineVersion", S_TOKEN_TYPE::VAR_INTEGER},

    // Not yet implemented
    {2, "FindClass", S_TOKEN_TYPE::VAR_INTEGER},
    {1, "FindClassNext", S_TOKEN_TYPE::VAR_INTEGER},
};

static constexpr uint32_t GetInternalFunctionArgumentsNum(uint32_t code) {
    if (code > IntFuncTable.size()) {
        throw std::logic_error("Internal function code cannot can not be greater than the function count");
    }
    return IntFuncTable[code].dwArgsNum;
}

enum FUNCTION_CODE
{
    FUNC_RAND,
    FUNC_FRAND,
    FUNC_CREATE_CLASS,
    FUNC_CREATE_Entity,
    FUNC_DELETE_Entity,
    FUNC_SET_EVENT_HANDLER,
    FUNC_EXIT_PROGRAM,
    FUNC_GET_EVENTDATA,
    // FUNC_EXECUTE,
    FUNC_STOP,
    FUNC_SEND_MESSAGE,
    FUNC_LOAD_SEGMENT,
    FUNC_UNLOAD_SEGMENT,
    FUNC_TRACE,
    FUNC_MAKE_INT,
    FUNC_MAKE_FLOAT,
    FUNC_LAYER_CREATE,
    FUNC_LAYER_DELETE,
    FUNC_LAYER_DELETE_CONTENT,
    FUNC_LAYER_SET_REALIZE,
    FUNC_LAYER_SET_EXECUTE,
    FUNC_LAYER_SET_MESSAGES,
    FUNC_LAYER_ADDOBJECT,
    FUNC_LAYER_DELOBJECT,
    FUNC_LAYER_FREEZE,
    FUNC_ABS,
    FUNC_SQRT,
    FUNC_SQR,
    FUNC_SIN,
    FUNC_COS,
    FUNC_TAN,
    FUNC_ATAN,
    FUNC_ATAN2,
    FUNC_ASIN,
    FUNC_ACOS,
    FUNC_DELETE_ATTRIBUTE,
    FUNC_SEGMENT_IS_LOADED,
    FUNC_GET_ATTRIBUTES_NUM,
    FUNC_GET_ATTRIBUTE_BYN,
    FUNC_GET_ATTRIBUTE_NAME,
    FUNC_DEL_EVENT_HANDLER,
    FUNC_Entity_UPDATE,
    FUNC_IS_Entity_LOADED,
    FUNC_DUMP_ATTRIBUTES,
    FUNC_STI,
    FUNC_STF,
    FUNC_CHECK_ATTRIBUTE,
    FUNC_ARGB,
    FUNC_DELETE_ENTITIES,
    FUNC_CLEAR_EVENTS,
    FUNC_SAVEENGINESTATE,
    FUNC_LOADENGINESTATE,
    FUNC_EVENT,
    FUNC_POSTEVENT,
    FUNC_FTS,
    FUNC_CLEAR_POST_EVENTS,
    FUNC_SET_ARRAY_SIZE,
    FUNC_GET_ATTRIBUTE_VALUE,
    FUNC_VARTYPE,
    FUNC_BREAKPOINT,
    FUNC_POW,
    FUNC_COPYATTRIBUTES,
//    FUNC_GETEntity,
    FUNC_GETEntityNEXT,
    FUNC_GETEntityNAME,
    FUNC_STRCUT,
    FUNC_FINDSUBSTR,
    FUNC_CLEARREF,
    FUNC_STRLEN,
    // FUNC_SETSAVEDATA,
    // FUNC_GETSAVEDATA,
    FUNC_GETDELTATIME,
    FUNC_EVENTSBREAK,
    FUNC_SHL,
    FUNC_SHR,
    FUNC_AND,
    FUNC_OR,
    FUNC_DELETEENTITIESBYTYPE,
    FUNC_CREATE_CONTROL,
    FUNC_DELETE_CONTROL,
    FUNC_MAP_CONTROL,
    FUNC_SET_CONTROL_FLAGS,
    FUNC_CLEAR_Entity_AP,
    FUNC_GET_ARRAY_SIZE,
    FUNC_GETTARGETPLATFORM,
    FUNC_GETENTITY,
    FUNC_FINDENTITY,
    FUNC_FINDENTITYNEXT,
    FUNC_GETSYMBOL,
    FUNC_ISDIGIT,
    FUNC_SAVEVARIABLE,
    FUNC_LOADVARIABLE,
    FUNC_SET_CONTROL_TRESHOLD,
    FUNC_LOCK_CONTROL,
    FUNC_TEST_REF,
    FUNC_SETTIMESCALE,
    FUNC_CHECKFUNCTION,
    FUNC_GETENGINEVERSION,
};
